name: m_store
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.5.3






#----------------PACKAGES-------------
dependencies:
  flutter:
    sdk: flutter

  #----- utility package--------------
  intl: ^0.20.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  logger: ^2.4.0
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0

  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #state Management
  get: ^4.6.6
  get_storage: ^2.1.1

  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.4.0






#----------------PACKAGES END -----------

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  flutter_lints: ^4.0.0





flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/images/user/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 800
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
