// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE8DHGtD7i8quSogL0ebhtSe2DJO_nyj8',
    appId: '1:1004028023050:web:274311446f77017fe7eaf3',
    messagingSenderId: '1004028023050',
    projectId: 'm-store-e-commerce-82d13',
    authDomain: 'm-store-e-commerce-82d13.firebaseapp.com',
    storageBucket: 'm-store-e-commerce-82d13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_S_WuK20TCcn414l8snfFxeSs2o_X3ck',
    appId: '1:1004028023050:android:03d23d61dddf7480e7eaf3',
    messagingSenderId: '1004028023050',
    projectId: 'm-store-e-commerce-82d13',
    storageBucket: 'm-store-e-commerce-82d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQV7-pQaGwWSsp8Tq90AjTQJqXra3vFc',
    appId: '1:1004028023050:ios:28f5100474b44051e7eaf3',
    messagingSenderId: '1004028023050',
    projectId: 'm-store-e-commerce-82d13',
    storageBucket: 'm-store-e-commerce-82d13.firebasestorage.app',
    iosBundleId: 'com.example.mStore',
  );
}
